### ISSUE TITLE
Username and password error?

### ISSUE THREAD

**Issue by shaunc869** [kbni/pycw#1]
Hi!

I am getting Server was unable to process request. ---> Exception has been thrown by the target of an invocation. ---> Username or password is incorrect

the server is staging.connectwisedev.com and I can login to ConnectWise with the same credentials, any tips? Thanks!

**Comment by kbni** [comment]
Hi Shaun,

You need to use a Integrator Login for this, this is separate from
Users/Members. To create an integrator login, check out the 'Integrator
Login' setup table.

Cheers,
kbni

**Comment by shaunc869** [comment]
Awesome, thanks for the help!
